-- NovaKitPVP online tierlist schema
-- Run this once in the Supabase SQL editor for the project connected to Vercel.

create extension if not exists pgcrypto;

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (name ~ '^[A-Za-z0-9_]{3,16}$'),
  region text not null default 'EU' check (region in ('EU','NA','AS','AU','SA','ME')),
  avatar_url text,
  minecraft_uuid text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_tiers (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.players(id) on delete cascade,
  gamemode text not null check (gamemode in ('sword','mace','vanilla','spearmace','diasmp','nethpot','diapot','cart','uhc','nethsmp')),
  active_tier text not null default 'Unranked' check (active_tier in ('HT1','LT1','HT2','LT2','HT3','LT3','HT4','LT4','HT5','LT5','Unranked')),
  peak_tier text check (peak_tier is null or peak_tier in ('HT1','LT1','HT2','LT2','HT3','LT3','HT4','LT4','HT5','LT5')),
  retired_tier text check (retired_tier is null or retired_tier in ('RHT1','RLT1','RHT2','RLT2')),
  updated_at timestamptz not null default now(),
  unique (player_id, gamemode)
);

create table if not exists public.staff_profiles (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  minecraft_uuid text unique,
  minecraft_username text unique,
  role text not null default 'pending' check (role in ('pending','tier_staff','owner')),
  verified boolean not null default false,
  linked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.link_requests (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  code text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_auth_user_id uuid,
  actor_minecraft_username text,
  action text not null,
  player_id uuid,
  change jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_player_tiers_player on public.player_tiers(player_id);
create index if not exists idx_player_tiers_mode on public.player_tiers(gamemode);
create index if not exists idx_link_requests_code on public.link_requests(code);
create index if not exists idx_audit_created on public.audit_logs(created_at desc);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_verified_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.staff_profiles
    where auth_user_id = auth.uid()
      and verified = true
      and role in ('tier_staff','owner')
  );
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.staff_profiles
    where auth_user_id = auth.uid()
      and verified = true
      and role = 'owner'
  );
$$;

create or replace function public.current_staff_name()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select minecraft_username from public.staff_profiles where auth_user_id = auth.uid() limit 1;
$$;

create or replace function public.ensure_mode_rows()
returns trigger language plpgsql security definer set search_path = '' as $$
declare m text;
begin
  foreach m in array array['sword','mace','vanilla','spearmace','diasmp','nethpot','diapot','cart','uhc','nethsmp'] loop
    insert into public.player_tiers(player_id, gamemode) values(new.id,m)
    on conflict (player_id,gamemode) do nothing;
  end loop;
  return new;
end;
$$;

create or replace function public.audit_player_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare actor text;
begin
  actor := public.current_staff_name();
  if tg_op = 'INSERT' then
    insert into public.audit_logs(actor_auth_user_id,actor_minecraft_username,action,player_id,change)
    values(auth.uid(),actor,'PLAYER_CREATED',new.id,jsonb_build_object('after',to_jsonb(new)));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.audit_logs(actor_auth_user_id,actor_minecraft_username,action,player_id,change)
    values(auth.uid(),actor,'PLAYER_UPDATED',new.id,jsonb_build_object('before',to_jsonb(old),'after',to_jsonb(new)));
    return new;
  else
    insert into public.audit_logs(actor_auth_user_id,actor_minecraft_username,action,player_id,change)
    values(auth.uid(),actor,'PLAYER_DELETED',old.id,jsonb_build_object('before',to_jsonb(old)));
    return old;
  end if;
end;
$$;

create or replace function public.audit_tier_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare actor text;
begin
  actor := public.current_staff_name();
  if tg_op = 'INSERT' then
    insert into public.audit_logs(actor_auth_user_id,actor_minecraft_username,action,player_id,change)
    values(auth.uid(),actor,'TIER_CREATED',new.player_id,jsonb_build_object('gamemode',new.gamemode,'after',to_jsonb(new)));
    return new;
  elsif tg_op = 'UPDATE' then
    if old.active_tier is distinct from new.active_tier
       or old.peak_tier is distinct from new.peak_tier
       or old.retired_tier is distinct from new.retired_tier then
      insert into public.audit_logs(actor_auth_user_id,actor_minecraft_username,action,player_id,change)
      values(auth.uid(),actor,'TIER_UPDATED',new.player_id,
        jsonb_build_object('gamemode',new.gamemode,
          'before',jsonb_build_object('active',old.active_tier,'peak',old.peak_tier,'retired',old.retired_tier),
          'after',jsonb_build_object('active',new.active_tier,'peak',new.peak_tier,'retired',new.retired_tier)));
    end if;
    return new;
  else
    insert into public.audit_logs(actor_auth_user_id,actor_minecraft_username,action,player_id,change)
    values(auth.uid(),actor,'TIER_DELETED',old.player_id,jsonb_build_object('gamemode',old.gamemode,'before',to_jsonb(old)));
    return old;
  end if;
end;
$$;

create or replace function public.create_link_request()
returns table(code text, expires_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare generated text;
declare expiry timestamptz;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  update public.link_requests set used_at = now()
    where auth_user_id = auth.uid() and used_at is null;
  loop
    generated := 'NOVA-' || upper(substr(encode(extensions.gen_random_bytes(8),'hex'),1,6));
    exit when not exists(select 1 from public.link_requests lr where lr.code = generated);
  end loop;
  expiry := now() + interval '10 minutes';
  insert into public.link_requests(auth_user_id,code,expires_at) values(auth.uid(),generated,expiry);
  return query select generated, expiry;
end;
$$;

create or replace function public.reset_all_tiers()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  update public.player_tiers set active_tier='Unranked', peak_tier=null, retired_tier=null, updated_at=now();
  insert into public.audit_logs(actor_auth_user_id,actor_minecraft_username,action,change)
  values(auth.uid(),public.current_staff_name(),'RESET_ALL_TIERS',jsonb_build_object('scope','all players'));
end;
$$;

create or replace function public.factory_reset_tierlist()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  insert into public.audit_logs(actor_auth_user_id,actor_minecraft_username,action,change)
  values(auth.uid(),public.current_staff_name(),'FACTORY_RESET_TIERLIST',jsonb_build_object('scope','all players and tiers'));
  delete from public.players;
end;
$$;

-- Timestamps
DROP TRIGGER IF EXISTS trg_players_touch ON public.players;
create trigger trg_players_touch before update on public.players for each row execute function public.touch_updated_at();
DROP TRIGGER IF EXISTS trg_tiers_touch ON public.player_tiers;
create trigger trg_tiers_touch before update on public.player_tiers for each row execute function public.touch_updated_at();
DROP TRIGGER IF EXISTS trg_staff_touch ON public.staff_profiles;
create trigger trg_staff_touch before update on public.staff_profiles for each row execute function public.touch_updated_at();

-- Create all ten tier rows for every new player.
DROP TRIGGER IF EXISTS trg_player_modes ON public.players;
create trigger trg_player_modes after insert on public.players for each row execute function public.ensure_mode_rows();

-- Audit changes made through authenticated staff sessions.
DROP TRIGGER IF EXISTS trg_players_audit ON public.players;
create trigger trg_players_audit after insert or update or delete on public.players for each row execute function public.audit_player_change();
DROP TRIGGER IF EXISTS trg_tiers_audit ON public.player_tiers;
create trigger trg_tiers_audit after insert or update or delete on public.player_tiers for each row execute function public.audit_tier_change();

-- Row Level Security
alter table public.players enable row level security;
alter table public.player_tiers enable row level security;
alter table public.staff_profiles enable row level security;
alter table public.link_requests enable row level security;
alter table public.audit_logs enable row level security;

DROP POLICY IF EXISTS "Public can read players" ON public.players;
create policy "Public can read players" on public.players for select using (true);
DROP POLICY IF EXISTS "Owners can insert players" ON public.players;
create policy "Owners can insert players" on public.players for insert to authenticated with check (public.is_owner());
DROP POLICY IF EXISTS "Owners can update players" ON public.players;
create policy "Owners can update players" on public.players for update to authenticated using (public.is_owner()) with check (public.is_owner());
DROP POLICY IF EXISTS "Owners can delete players" ON public.players;
create policy "Owners can delete players" on public.players for delete to authenticated using (public.is_owner());

DROP POLICY IF EXISTS "Public can read tiers" ON public.player_tiers;
create policy "Public can read tiers" on public.player_tiers for select using (true);
DROP POLICY IF EXISTS "Verified staff can insert tiers" ON public.player_tiers;
create policy "Verified staff can insert tiers" on public.player_tiers for insert to authenticated with check (public.is_verified_staff());
DROP POLICY IF EXISTS "Verified staff can update tiers" ON public.player_tiers;
create policy "Verified staff can update tiers" on public.player_tiers for update to authenticated using (public.is_verified_staff()) with check (public.is_verified_staff());
DROP POLICY IF EXISTS "Owners can delete tiers" ON public.player_tiers;
create policy "Owners can delete tiers" on public.player_tiers for delete to authenticated using (public.is_owner());

DROP POLICY IF EXISTS "Staff can read own profile" ON public.staff_profiles;
create policy "Staff can read own profile" on public.staff_profiles for select to authenticated using (auth_user_id = auth.uid() or public.is_owner());

DROP POLICY IF EXISTS "Users can read own link requests" ON public.link_requests;
create policy "Users can read own link requests" on public.link_requests for select to authenticated using (auth_user_id = auth.uid());

DROP POLICY IF EXISTS "Owners can read audit logs" ON public.audit_logs;
create policy "Owners can read audit logs" on public.audit_logs for select to authenticated using (public.is_owner());

-- RPC permissions
revoke all on function public.is_verified_staff() from public;
revoke all on function public.is_owner() from public;
revoke all on function public.current_staff_name() from public;
grant execute on function public.is_verified_staff() to authenticated;
grant execute on function public.is_owner() to authenticated;
grant execute on function public.current_staff_name() to authenticated;
grant execute on function public.create_link_request() to authenticated;
grant execute on function public.reset_all_tiers() to authenticated;
grant execute on function public.factory_reset_tierlist() to authenticated;

grant select on public.players, public.player_tiers to anon, authenticated;
grant select on public.staff_profiles, public.link_requests, public.audit_logs to authenticated;
grant insert, update, delete on public.players, public.player_tiers to authenticated;

-- Realtime updates for the public rankings.
do $$
begin
  begin alter publication supabase_realtime add table public.players; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.player_tiers; exception when duplicate_object then null; end;
end $$;

-- ===== Email-based staff roles + customizable icons =====
create table if not exists public.owner_emails (email text primary key);
alter table public.owner_emails enable row level security;
insert into public.owner_emails(email) values
('geraldmcbride60@gmail.com'),('poppymacedu@gmail.com')
on conflict (email) do nothing;
revoke all on public.owner_emails from anon, authenticated;

create table if not exists public.admin_emails (
  email text primary key,
  created_at timestamptz not null default now()
);
alter table public.admin_emails enable row level security;
revoke all on public.admin_emails from anon, authenticated;

create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.owner_emails oe
    where lower(oe.email)=lower(coalesce(auth.jwt() ->> 'email',''))
  );
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select public.is_owner() or exists (
    select 1 from public.admin_emails ae
    where lower(ae.email)=lower(coalesce(auth.jwt() ->> 'email',''))
  );
$$;

create or replace function public.is_verified_staff()
returns boolean language sql stable security definer set search_path = '' as $$
  select public.is_admin();
$$;

create or replace function public.current_staff_name()
returns text language sql stable security definer set search_path = '' as $$
  select lower(coalesce(auth.jwt() ->> 'email',''));
$$;

create or replace function public.get_my_access()
returns table(email text, role text)
language sql stable security definer set search_path = '' as $$
  select lower(coalesce(auth.jwt() ->> 'email',''))::text,
    case when public.is_owner() then 'owner'::text
         when public.is_admin() then 'admin'::text
         else 'none'::text end
  where auth.uid() is not null;
$$;

revoke all on function public.is_admin() from public, anon;
revoke all on function public.get_my_access() from public, anon;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.get_my_access() to authenticated;

-- Admins can update/delete individual players, but only Owners can create players.
drop policy if exists "Owners can update players" on public.players;
drop policy if exists "Admins can update players" on public.players;
create policy "Admins can update players" on public.players for update to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Owners can delete players" on public.players;
drop policy if exists "Admins can delete players" on public.players;
create policy "Admins can delete players" on public.players for delete to authenticated using (public.is_admin());

drop policy if exists "Verified staff can insert tiers" on public.player_tiers;
drop policy if exists "Admins can insert tiers" on public.player_tiers;
create policy "Admins can insert tiers" on public.player_tiers for insert to authenticated with check (public.is_admin());
drop policy if exists "Verified staff can update tiers" on public.player_tiers;
drop policy if exists "Admins can update tiers" on public.player_tiers;
create policy "Admins can update tiers" on public.player_tiers for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Owners can delete tiers" on public.player_tiers;
drop policy if exists "Admins can delete tiers" on public.player_tiers;
create policy "Admins can delete tiers" on public.player_tiers for delete to authenticated using (public.is_admin());

-- Owner-only log clear.
drop policy if exists "Owners can clear audit logs" on public.audit_logs;
create policy "Owners can clear audit logs" on public.audit_logs for delete to authenticated using (public.is_owner());
create or replace function public.clear_audit_logs()
returns void language plpgsql security definer set search_path = '' as $$
declare actor_id uuid; declare actor_name text;
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  actor_id:=auth.uid(); actor_name:=public.current_staff_name();
  delete from public.audit_logs;
  insert into public.audit_logs(actor_auth_user_id,actor_minecraft_username,action,change)
  values(actor_id,actor_name,'AUDIT_LOG_CLEARED',jsonb_build_object('scope','all previous audit entries'));
end; $$;
revoke all on function public.clear_audit_logs() from public, anon;
grant execute on function public.clear_audit_logs() to authenticated;

-- Owner-editable site/kit/rank icons. Values may be emoji/symbols or https image URLs.
create table if not exists public.site_assets (
  asset_key text primary key,
  asset_value text not null default '',
  updated_at timestamptz not null default now()
);
alter table public.site_assets enable row level security;
drop policy if exists "Public can read site assets" on public.site_assets;
create policy "Public can read site assets" on public.site_assets for select using (true);
drop policy if exists "Owners can manage site assets" on public.site_assets;
create policy "Owners can manage site assets" on public.site_assets for all to authenticated using (public.is_owner()) with check (public.is_owner());
grant select on public.site_assets to anon, authenticated;
grant insert, update, delete on public.site_assets to authenticated;
insert into public.site_assets(asset_key,asset_value) values
('brand_logo','N'),('kit_sword','⚔'),('kit_mace','◆'),('kit_vanilla','✦'),('kit_spearmace','➹'),('kit_diasmp','◇'),
('kit_nethpot','◈'),('kit_diapot','◉'),('kit_cart','▣'),('kit_uhc','❤'),('kit_nethsmp','⬢'),
('rank_grandmaster','✹'),('rank_master','◆'),('rank_ace','✦'),('rank_specialist','✧'),('rank_cadet','◇'),('rank_novice','◈'),('rank_rookie','·')
on conflict (asset_key) do nothing;

do $$ begin
  begin alter publication supabase_realtime add table public.site_assets; exception when duplicate_object then null; end;
end $$;

-- Minecraft link codes are no longer used.
revoke execute on function public.create_link_request() from authenticated;
